### ISSUE TITLE
Change name of code dir to semasioFlowLib?

### ISSUE THREAD

**Issue by KrisHeylen** [montesmariana/semasioFlow#9]
When cloning the semasioFlow repo locally, git creates a directory ./semasioFlow and the actual code is in a subdir with the same name, so `./semasioFlow/semasioFlow`. This is a bit confusing. I am not sure what good practice is in this case but I've seen my programmer colleagues at INT use `Repo name` + `Lib` for the directory with the actual code in it. So in this case  within repo dir `semasioFlow` , the directory with the code would be named `semasioFlowLib/`

**Comment by montesmariana** [comment]
I understand that changing the name of the directory with the code also requires changing the reference to the package in every script inside the package and the notebooks... I'm a bit reluctant to do that. That is why I would prefer emphasizing on the instruction of "changing your path to the path to your repository" and that's it. We can give examples in any case.

**Comment by KrisHeylen** [comment]
fair enough!
